-- migrate:up
ALTER TABLE keyword ALTER COLUMN keyword_id SET GENERATED BY DEFAULT;
INSERT INTO keyword(keyword_id, keyword)
VALUES(0, 'corpse')
ON CONFLICT (keyword_id) DO NOTHING;

-- migrate:down
DELETE FROM keyword WHERE id = 0;
ALTER TABLE keyword ALTER COLUMN keyword_id SET GENERATED ALWAYS;