name = "lore"
version = "0.0.1"

# Fill out these fields if you intend to generate HTML documentation or publish
# your project to the Hex package manager.
#
# description = ""
# licences = ["Apache-2.0"]
# repository = { type = "github", user = "", repo = "" }
# links = [{ title = "Website", href = "" }]
#
# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
logging = ">= 1.3.0 and < 2.0.0"
party = ">= 1.0.6 and < 2.0.0"
glisten = ">= 8.0.0 and < 9.0.0"
gleam_erlang = ">= 1.1.0 and < 2.0.0"
gleam_otp = ">= 1.0.0 and < 2.0.0"
gleam_stdlib = ">= 0.60.0 and < 1.0.0"
glets = { git = "https://github.com/i-am-tanni/glets", ref = "80e15c2" }
hyphenation = { git = "https://github.com/i-am-tanni/hyphenation", ref = "74bfb9f" }
simplifile = ">= 2.3.0 and < 3.0.0"
pog = ">= 4.1.0 and < 5.0.0"
envoy = ">= 1.0.2 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
squirrel = ">= 4.4.1 and < 5.0.0"
