\restrict dbmate

-- Dumped from database version 17.7 (Postgres.app)
-- Dumped by pg_dump version 17.7 (Homebrew)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

--
-- Name: access_state; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.access_state AS ENUM (
    'closed',
    'open'
);


--
-- Name: role_enum; Type: TYPE; Schema: public; Owner: -
--

CREATE TYPE public.role_enum AS ENUM (
    'admin',
    'user'
);


SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: account; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.account (
    account_id integer NOT NULL,
    name character varying(255) NOT NULL,
    password_hash text NOT NULL,
    role public.role_enum NOT NULL
);


--
-- Name: account_account_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.account ALTER COLUMN account_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.account_account_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: container_kit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.container_kit (
    container_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT chk_cannot_hold_self CHECK ((container_id <> item_id)),
    CONSTRAINT container_kit_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: door; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.door (
    door_id integer NOT NULL,
    access_state public.access_state NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: door_door_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.door ALTER COLUMN door_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.door_door_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: door_side; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.door_side (
    door_side_id integer NOT NULL,
    door_id integer NOT NULL,
    exit_id integer NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: door_side_door_side_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.door_side ALTER COLUMN door_side_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.door_side_door_side_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: exit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.exit (
    exit_id integer NOT NULL,
    keyword character varying(32) NOT NULL,
    from_room_id integer NOT NULL,
    to_room_id integer NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: exit_exit_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.exit ALTER COLUMN exit_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.exit_exit_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: inventory_kit; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.inventory_kit (
    mobile_id integer NOT NULL,
    item_id integer NOT NULL,
    quantity integer NOT NULL,
    CONSTRAINT inventory_kit_quantity_check CHECK ((quantity >= 0))
);


--
-- Name: item; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item (
    item_id integer NOT NULL,
    name character varying(255) NOT NULL,
    short text NOT NULL,
    long text NOT NULL,
    keywords character varying(255)[] NOT NULL
);


--
-- Name: item_instance; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_instance (
    item_instance_id integer NOT NULL,
    item_id integer NOT NULL,
    is_active boolean NOT NULL
);


--
-- Name: item_instance_item_instance_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item_instance ALTER COLUMN item_instance_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.item_instance_item_instance_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_item_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item ALTER COLUMN item_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.item_item_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: item_spawn; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.item_spawn (
    item_spawn_id integer NOT NULL,
    item_id integer NOT NULL,
    room_id integer NOT NULL,
    spawn_group_id integer NOT NULL
);


--
-- Name: item_spawn_item_spawn_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.item_spawn ALTER COLUMN item_spawn_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.item_spawn_item_spawn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: keyword; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.keyword (
    keyword_id integer NOT NULL,
    keyword character varying(255) NOT NULL
);


--
-- Name: keyword_keyword_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.keyword ALTER COLUMN keyword_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.keyword_keyword_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mob_spawn; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mob_spawn (
    mob_spawn_id integer NOT NULL,
    spawn_group_id integer NOT NULL,
    mobile_id integer NOT NULL,
    room_id integer NOT NULL
);


--
-- Name: mob_spawn_mob_spawn_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mob_spawn ALTER COLUMN mob_spawn_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.mob_spawn_mob_spawn_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: mobile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.mobile (
    mobile_id integer NOT NULL,
    room_id integer NOT NULL,
    name character varying(255) NOT NULL,
    short text NOT NULL,
    keywords character varying(255)[] NOT NULL
);


--
-- Name: mobile_mobile_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.mobile ALTER COLUMN mobile_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.mobile_mobile_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: room; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.room (
    room_id integer NOT NULL,
    name character varying(255) NOT NULL,
    zone_id integer NOT NULL,
    symbol character varying(255) NOT NULL,
    x integer NOT NULL,
    y integer NOT NULL,
    z integer NOT NULL,
    description text NOT NULL
);


--
-- Name: room_room_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.room ALTER COLUMN room_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.room_room_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: schema_migrations; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schema_migrations (
    version character varying NOT NULL
);


--
-- Name: social; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.social (
    social_id integer NOT NULL,
    command text NOT NULL,
    char_auto text NOT NULL,
    char_no_arg text NOT NULL,
    char_found text NOT NULL,
    others_auto text NOT NULL,
    others_found text NOT NULL,
    others_no_arg text NOT NULL,
    vict_found text NOT NULL
);


--
-- Name: social_social_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.social ALTER COLUMN social_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.social_social_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: spawn_group; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.spawn_group (
    spawn_group_id integer NOT NULL,
    reset_freq integer NOT NULL,
    is_enabled boolean NOT NULL,
    is_despawn_on_reset boolean NOT NULL
);


--
-- Name: spawn_group_spawn_group_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.spawn_group ALTER COLUMN spawn_group_id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.spawn_group_spawn_group_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: zone; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.zone (
    zone_id integer NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: zones_zone_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.zone ALTER COLUMN zone_id ADD GENERATED ALWAYS AS IDENTITY (
    SEQUENCE NAME public.zones_zone_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: account account_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT account_pkey PRIMARY KEY (account_id);


--
-- Name: container_kit container_kit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.container_kit
    ADD CONSTRAINT container_kit_pkey PRIMARY KEY (container_id, item_id);


--
-- Name: door door_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.door
    ADD CONSTRAINT door_pkey PRIMARY KEY (door_id);


--
-- Name: door_side door_side_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.door_side
    ADD CONSTRAINT door_side_pkey PRIMARY KEY (door_side_id);


--
-- Name: exit exit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT exit_pkey PRIMARY KEY (exit_id);


--
-- Name: inventory_kit inventory_kit_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_kit
    ADD CONSTRAINT inventory_kit_pkey PRIMARY KEY (mobile_id, item_id);


--
-- Name: item_instance item_instance_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_instance
    ADD CONSTRAINT item_instance_pkey PRIMARY KEY (item_instance_id);


--
-- Name: item item_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item
    ADD CONSTRAINT item_pkey PRIMARY KEY (item_id);


--
-- Name: item_spawn item_spawn_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spawn
    ADD CONSTRAINT item_spawn_pkey PRIMARY KEY (item_spawn_id);


--
-- Name: keyword keyword_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.keyword
    ADD CONSTRAINT keyword_pkey PRIMARY KEY (keyword_id);


--
-- Name: keyword kw_unique; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.keyword
    ADD CONSTRAINT kw_unique UNIQUE (keyword);


--
-- Name: mob_spawn mob_spawn_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mob_spawn
    ADD CONSTRAINT mob_spawn_pkey PRIMARY KEY (mob_spawn_id);


--
-- Name: mobile mobile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mobile
    ADD CONSTRAINT mobile_pkey PRIMARY KEY (mobile_id);


--
-- Name: room room_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT room_pkey PRIMARY KEY (room_id);


--
-- Name: schema_migrations schema_migrations_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schema_migrations
    ADD CONSTRAINT schema_migrations_pkey PRIMARY KEY (version);


--
-- Name: social social_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.social
    ADD CONSTRAINT social_pkey PRIMARY KEY (social_id);


--
-- Name: spawn_group spawn_group_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.spawn_group
    ADD CONSTRAINT spawn_group_pkey PRIMARY KEY (spawn_group_id);


--
-- Name: account uq_account_name; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.account
    ADD CONSTRAINT uq_account_name UNIQUE (name);


--
-- Name: exit uq_room_keyword; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT uq_room_keyword UNIQUE (from_room_id, keyword);


--
-- Name: zone zones_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.zone
    ADD CONSTRAINT zones_pkey PRIMARY KEY (zone_id);


--
-- Name: container_kit fk_container_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.container_kit
    ADD CONSTRAINT fk_container_id FOREIGN KEY (container_id) REFERENCES public.item(item_id) ON DELETE CASCADE;


--
-- Name: door_side fk_door_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.door_side
    ADD CONSTRAINT fk_door_id FOREIGN KEY (door_id) REFERENCES public.door(door_id) ON DELETE CASCADE;


--
-- Name: door_side fk_exit_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.door_side
    ADD CONSTRAINT fk_exit_id FOREIGN KEY (exit_id) REFERENCES public.exit(exit_id) ON DELETE CASCADE;


--
-- Name: container_kit fk_item_contained; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.container_kit
    ADD CONSTRAINT fk_item_contained FOREIGN KEY (item_id) REFERENCES public.item(item_id) ON DELETE CASCADE;


--
-- Name: item_instance fk_item_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_instance
    ADD CONSTRAINT fk_item_id FOREIGN KEY (item_id) REFERENCES public.item(item_id) ON DELETE CASCADE;


--
-- Name: inventory_kit fk_item_in_inventory_kit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_kit
    ADD CONSTRAINT fk_item_in_inventory_kit FOREIGN KEY (item_id) REFERENCES public.item(item_id) ON DELETE CASCADE;


--
-- Name: item_spawn fk_item_spawn_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spawn
    ADD CONSTRAINT fk_item_spawn_id FOREIGN KEY (item_id) REFERENCES public.item(item_id) ON DELETE CASCADE;


--
-- Name: mob_spawn fk_mobile_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mob_spawn
    ADD CONSTRAINT fk_mobile_id FOREIGN KEY (mobile_id) REFERENCES public.mobile(mobile_id) ON DELETE CASCADE;


--
-- Name: inventory_kit fk_mobile_inventory_kit; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.inventory_kit
    ADD CONSTRAINT fk_mobile_inventory_kit FOREIGN KEY (mobile_id) REFERENCES public.mobile(mobile_id) ON DELETE CASCADE;


--
-- Name: exit fk_room_from; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fk_room_from FOREIGN KEY (from_room_id) REFERENCES public.room(room_id) ON DELETE CASCADE;


--
-- Name: item_spawn fk_room_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spawn
    ADD CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE;


--
-- Name: mob_spawn fk_room_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mob_spawn
    ADD CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE;


--
-- Name: mobile fk_room_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mobile
    ADD CONSTRAINT fk_room_id FOREIGN KEY (room_id) REFERENCES public.room(room_id) ON DELETE CASCADE;


--
-- Name: exit fk_room_to; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.exit
    ADD CONSTRAINT fk_room_to FOREIGN KEY (to_room_id) REFERENCES public.room(room_id) ON DELETE CASCADE;


--
-- Name: mob_spawn fk_spawn_group; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.mob_spawn
    ADD CONSTRAINT fk_spawn_group FOREIGN KEY (spawn_group_id) REFERENCES public.spawn_group(spawn_group_id) ON DELETE CASCADE;


--
-- Name: item_spawn fk_spawn_group_id; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.item_spawn
    ADD CONSTRAINT fk_spawn_group_id FOREIGN KEY (spawn_group_id) REFERENCES public.spawn_group(spawn_group_id) ON DELETE CASCADE;


--
-- Name: room fk_zone; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.room
    ADD CONSTRAINT fk_zone FOREIGN KEY (zone_id) REFERENCES public.zone(zone_id) ON DELETE CASCADE;


--
-- PostgreSQL database dump complete
--

\unrestrict dbmate


--
-- Dbmate schema migrations
--

INSERT INTO public.schema_migrations (version) VALUES
    ('20260203112222');
